### ISSUE TITLE
Blinking in Mozilla Firefox 50.1.0

### ISSUE THREAD

**Issue by temapanf** [ptv-logistics/Leaflet.NonTiledLayer#18]
http://ptv-logistics.github.io/Leaflet.NonTiledLayer/
When moving on the map nonTiled layers are blinking in Mozilla Firefox 50.1.0. In Chrome all right.

**Comment by xserverinternet** [comment]
Hi, i can also reproduce it with 49.0.1. Seems it has to do with the flipping of the back- and foreground-buffer. Will look for an alternative.

**Comment by temapanf** [comment]
I tried to Mozilla Firefox 43.0.1 also doing well. Perhaps the FF update will solve the problem.

**Comment by xserverinternet** [comment]
Hi,

It seems that the issue came with v45, see this thread https://bugzilla.mozilla.org/show_bug.cgi?id=705826 The thread indicates the Firefox users not very satisfied with this behaviour in general.

I couldn't find a simple workaround for it. The only workaround would be to use the canvas instead of an image. But this would need some elaborate work and maybe browser switches. 

So if the Firefox devs don't come around with a solution i can take a look at this after the holidays. I have some experience with dynamic canvas-layers :) http://ptv-logistics.github.io/xmas-server/

Oliver

**Comment by temapanf** [comment]
Thank you! Merry Christmas :)

**Comment by xserverinternet** [comment]
OK, i now use the canvas , which fixes the blinkng issue. The layer now also works for both Leaflet 1.0.  http://ptv-logistics.github.io/Leaflet.NonTiledLayer/index.html and 0.7. http://ptv-logistics.github.io/Leaflet.NonTiledLayer/test.0.7.html

The code detects the canvas automatically, so it should work on IE8 also. But i don't know if canvas works well on every browser. You can override it by setting the useCanvas option to true/false.

Oliver

**Comment by xserverinternet** [comment]
sorry - wrong commit! Now it should be flicker-free.

Oliver
